-- QiHabitSync: Supabase Database Setup
-- Run this in Supabase SQL Editor

create table habit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_name text not null, -- Stores 'Partner A' or 'Partner B'
  log_date date default current_date,
  water_oz int default 0,
  exercise_mins int default 0,
  intimacy boolean default false, -- Tracks intercourse
  sleep_hours numeric default 0,
  alcohol_units int default 0,
  bp_systolic int,
  bp_diastolic int,
  heart_rate int,
  mood_rating int, -- 1 to 5 scale
  stimulants_mg int default 0, -- e.g., Caffeine/Meds
  medications_taken boolean default false,
  food_notes text
);

-- Turn on Row Level Security (optional for testing, recommended for prod)
alter table habit_logs enable row level security;

-- Allow anyone with the anon key to read/insert (for simplicity in this demo)
-- NOTE: For production, you should restrict this to authenticated users
create policy "Public Access" on habit_logs for all using (true) with check (true);

-- Optional: Create indexes for better query performance
create index idx_habit_logs_user_date on habit_logs(user_name, log_date);
create index idx_habit_logs_log_date on habit_logs(log_date);
