/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appUsersRouteImport } from './routes/(app)/users'
import { Route as appTimelineRouteImport } from './routes/(app)/timeline'
import { Route as appTableDataRouteImport } from './routes/(app)/table-data'
import { Route as appSettingsRouteImport } from './routes/(app)/settings'
import { Route as appResourcesRouteImport } from './routes/(app)/resources'
import { Route as appReportsRouteImport } from './routes/(app)/reports'
import { Route as appPhasesRouteImport } from './routes/(app)/phases'
import { Route as appLibraryRouteImport } from './routes/(app)/library'
import { Route as appDashboardRouteImport } from './routes/(app)/dashboard'
import { Route as appAnalyticsRouteImport } from './routes/(app)/analytics'
import { Route as appAboutRouteImport } from './routes/(app)/about'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appUsersRoute = appUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => appRouteRoute,
} as any)
const appTimelineRoute = appTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => appRouteRoute,
} as any)
const appTableDataRoute = appTableDataRouteImport.update({
  id: '/table-data',
  path: '/table-data',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appResourcesRoute = appResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => appRouteRoute,
} as any)
const appReportsRoute = appReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => appRouteRoute,
} as any)
const appPhasesRoute = appPhasesRouteImport.update({
  id: '/phases',
  path: '/phases',
  getParentRoute: () => appRouteRoute,
} as any)
const appLibraryRoute = appLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appRouteRoute,
} as any)
const appAnalyticsRoute = appAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => appRouteRoute,
} as any)
const appAboutRoute = appAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof appAboutRoute
  '/analytics': typeof appAnalyticsRoute
  '/dashboard': typeof appDashboardRoute
  '/library': typeof appLibraryRoute
  '/phases': typeof appPhasesRoute
  '/reports': typeof appReportsRoute
  '/resources': typeof appResourcesRoute
  '/settings': typeof appSettingsRoute
  '/table-data': typeof appTableDataRoute
  '/timeline': typeof appTimelineRoute
  '/users': typeof appUsersRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/': typeof appIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof appAboutRoute
  '/analytics': typeof appAnalyticsRoute
  '/dashboard': typeof appDashboardRoute
  '/library': typeof appLibraryRoute
  '/phases': typeof appPhasesRoute
  '/reports': typeof appReportsRoute
  '/resources': typeof appResourcesRoute
  '/settings': typeof appSettingsRoute
  '/table-data': typeof appTableDataRoute
  '/timeline': typeof appTimelineRoute
  '/users': typeof appUsersRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/': typeof appIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/about': typeof appAboutRoute
  '/(app)/analytics': typeof appAnalyticsRoute
  '/(app)/dashboard': typeof appDashboardRoute
  '/(app)/library': typeof appLibraryRoute
  '/(app)/phases': typeof appPhasesRoute
  '/(app)/reports': typeof appReportsRoute
  '/(app)/resources': typeof appResourcesRoute
  '/(app)/settings': typeof appSettingsRoute
  '/(app)/table-data': typeof appTableDataRoute
  '/(app)/timeline': typeof appTimelineRoute
  '/(app)/users': typeof appUsersRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(app)/': typeof appIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/analytics'
    | '/dashboard'
    | '/library'
    | '/phases'
    | '/reports'
    | '/resources'
    | '/settings'
    | '/table-data'
    | '/timeline'
    | '/users'
    | '/login'
    | '/signup'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/analytics'
    | '/dashboard'
    | '/library'
    | '/phases'
    | '/reports'
    | '/resources'
    | '/settings'
    | '/table-data'
    | '/timeline'
    | '/users'
    | '/login'
    | '/signup'
    | '/'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/about'
    | '/(app)/analytics'
    | '/(app)/dashboard'
    | '/(app)/library'
    | '/(app)/phases'
    | '/(app)/reports'
    | '/(app)/resources'
    | '/(app)/settings'
    | '/(app)/table-data'
    | '/(app)/timeline'
    | '/(app)/users'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(app)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/users': {
      id: '/(app)/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof appUsersRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/timeline': {
      id: '/(app)/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof appTimelineRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/table-data': {
      id: '/(app)/table-data'
      path: '/table-data'
      fullPath: '/table-data'
      preLoaderRoute: typeof appTableDataRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/resources': {
      id: '/(app)/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof appResourcesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/reports': {
      id: '/(app)/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof appReportsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/phases': {
      id: '/(app)/phases'
      path: '/phases'
      fullPath: '/phases'
      preLoaderRoute: typeof appPhasesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/library': {
      id: '/(app)/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof appLibraryRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/analytics': {
      id: '/(app)/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof appAnalyticsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/about': {
      id: '/(app)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof appAboutRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appAboutRoute: typeof appAboutRoute
  appAnalyticsRoute: typeof appAnalyticsRoute
  appDashboardRoute: typeof appDashboardRoute
  appLibraryRoute: typeof appLibraryRoute
  appPhasesRoute: typeof appPhasesRoute
  appReportsRoute: typeof appReportsRoute
  appResourcesRoute: typeof appResourcesRoute
  appSettingsRoute: typeof appSettingsRoute
  appTableDataRoute: typeof appTableDataRoute
  appTimelineRoute: typeof appTimelineRoute
  appUsersRoute: typeof appUsersRoute
  appIndexRoute: typeof appIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAboutRoute: appAboutRoute,
  appAnalyticsRoute: appAnalyticsRoute,
  appDashboardRoute: appDashboardRoute,
  appLibraryRoute: appLibraryRoute,
  appPhasesRoute: appPhasesRoute,
  appReportsRoute: appReportsRoute,
  appResourcesRoute: appResourcesRoute,
  appSettingsRoute: appSettingsRoute,
  appTableDataRoute: appTableDataRoute,
  appTimelineRoute: appTimelineRoute,
  appUsersRoute: appUsersRoute,
  appIndexRoute: appIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
